### PR TITLE
fixed RN60 CocoaPods installation

### PR DESCRIPTION
**Pull request by netbull**

### CODE REVIEW

**Comment by NRamirezCR** [comment]
@netbull why don't we just move the existing podspec in `ios/RNAudioRecorderPlayer.podspec` to the root to avoid duplicates? Or we can just delete the old one.

**Comment by netbull** [comment]
I’m not really sure... I saw that it is the same in the package of react-native-cameraroll and it works...

**Comment by netbull** [comment]
@NRamirezCR yes, the podspec file inside `ios/` was not needed.

**Comment by netbull** [comment]
@hyochan any update on this?

**Comment by hyochan** [comment]
Related #99 #98

**Pull request merged**
